//package serialization.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: person.proto
//
//public final class PersonOuterClass {
//  private PersonOuterClass() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  public interface PersonOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:Person)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>string username = 1;</code>
//     */
//    String getUsername();
//    /**
//     * <code>string username = 1;</code>
//     */
//    com.google.protobuf.ByteString
//        getUsernameBytes();
//
//    /**
//     * <code>int32 age = 2;</code>
//     */
//    int getAge();
//
//    /**
//     * <code>string sex = 3;</code>
//     */
//    String getSex();
//    /**
//     * <code>string sex = 3;</code>
//     */
//    com.google.protobuf.ByteString
//        getSexBytes();
//  }
//  /**
//   * Protobuf type {@code Person}
//   */
//  public  static final class Person extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:Person)
//      PersonOrBuilder {
//  private static final long serialVersionUID = 0L;
//    // Use Person.newBuilder() to construct.
//    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private Person() {
//      username_ = "";
//      age_ = 0;
//      sex_ = "";
//    }
//
//    @Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return this.unknownFields;
//    }
//    private Person(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      int mutable_bitField0_ = 0;
//      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
//          com.google.protobuf.UnknownFieldSet.newBuilder();
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            default: {
//              if (!parseUnknownFieldProto3(
//                  input, unknownFields, extensionRegistry, tag)) {
//                done = true;
//              }
//              break;
//            }
//            case 10: {
//              String s = input.readStringRequireUtf8();
//
//              username_ = s;
//              break;
//            }
//            case 16: {
//
//              age_ = input.readInt32();
//              break;
//            }
//            case 26: {
//              String s = input.readStringRequireUtf8();
//
//              sex_ = s;
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return PersonOuterClass.internal_static_Person_descriptor;
//    }
//
//    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return PersonOuterClass.internal_static_Person_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              Person.class, Builder.class);
//    }
//
//    public static final int USERNAME_FIELD_NUMBER = 1;
//    private volatile Object username_;
//    /**
//     * <code>string username = 1;</code>
//     */
//    public String getUsername() {
//      Object ref = username_;
//      if (ref instanceof String) {
//        return (String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        String s = bs.toStringUtf8();
//        username_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string username = 1;</code>
//     */
//    public com.google.protobuf.ByteString
//        getUsernameBytes() {
//      Object ref = username_;
//      if (ref instanceof String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (String) ref);
//        username_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int AGE_FIELD_NUMBER = 2;
//    private int age_;
//    /**
//     * <code>int32 age = 2;</code>
//     */
//    public int getAge() {
//      return age_;
//    }
//
//    public static final int SEX_FIELD_NUMBER = 3;
//    private volatile Object sex_;
//    /**
//     * <code>string sex = 3;</code>
//     */
//    public String getSex() {
//      Object ref = sex_;
//      if (ref instanceof String) {
//        return (String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        String s = bs.toStringUtf8();
//        sex_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string sex = 3;</code>
//     */
//    public com.google.protobuf.ByteString
//        getSexBytes() {
//      Object ref = sex_;
//      if (ref instanceof String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (String) ref);
//        sex_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    private byte memoizedIsInitialized = -1;
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (!getUsernameBytes().isEmpty()) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
//      }
//      if (age_ != 0) {
//        output.writeInt32(2, age_);
//      }
//      if (!getSexBytes().isEmpty()) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sex_);
//      }
//      unknownFields.writeTo(output);
//    }
//
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (!getUsernameBytes().isEmpty()) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
//      }
//      if (age_ != 0) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeInt32Size(2, age_);
//      }
//      if (!getSexBytes().isEmpty()) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sex_);
//      }
//      size += unknownFields.getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @Override
//    public boolean equals(final Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof Person)) {
//        return super.equals(obj);
//      }
//      Person other = (Person) obj;
//
//      boolean result = true;
//      result = result && getUsername()
//          .equals(other.getUsername());
//      result = result && (getAge()
//          == other.getAge());
//      result = result && getSex()
//          .equals(other.getSex());
//      result = result && unknownFields.equals(other.unknownFields);
//      return result;
//    }
//
//    @Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
//      hash = (53 * hash) + getUsername().hashCode();
//      hash = (37 * hash) + AGE_FIELD_NUMBER;
//      hash = (53 * hash) + getAge();
//      hash = (37 * hash) + SEX_FIELD_NUMBER;
//      hash = (53 * hash) + getSex().hashCode();
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static Person parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static Person parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static Person parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static Person parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static Person parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static Person parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static Person parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static Person parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static Person parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static Person parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static Person parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static Person parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(Person prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code Person}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:Person)
//        PersonOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return PersonOuterClass.internal_static_Person_descriptor;
//      }
//
//      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return PersonOuterClass.internal_static_Person_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                Person.class, Builder.class);
//      }
//
//      // Construct using PersonOuterClass.Person.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      public Builder clear() {
//        super.clear();
//        username_ = "";
//
//        age_ = 0;
//
//        sex_ = "";
//
//        return this;
//      }
//
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return PersonOuterClass.internal_static_Person_descriptor;
//      }
//
//      public Person getDefaultInstanceForType() {
//        return Person.getDefaultInstance();
//      }
//
//      public Person build() {
//        Person result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      public Person buildPartial() {
//        Person result = new Person(this);
//        result.username_ = username_;
//        result.age_ = age_;
//        result.sex_ = sex_;
//        onBuilt();
//        return result;
//      }
//
//      public Builder clone() {
//        return (Builder) super.clone();
//      }
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.setField(field, value);
//      }
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return (Builder) super.clearField(field);
//      }
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return (Builder) super.clearOneof(oneof);
//      }
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, Object value) {
//        return (Builder) super.setRepeatedField(field, index, value);
//      }
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.addRepeatedField(field, value);
//      }
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof Person) {
//          return mergeFrom((Person)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(Person other) {
//        if (other == Person.getDefaultInstance()) return this;
//        if (!other.getUsername().isEmpty()) {
//          username_ = other.username_;
//          onChanged();
//        }
//        if (other.getAge() != 0) {
//          setAge(other.getAge());
//        }
//        if (!other.getSex().isEmpty()) {
//          sex_ = other.sex_;
//          onChanged();
//        }
//        this.mergeUnknownFields(other.unknownFields);
//        onChanged();
//        return this;
//      }
//
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        Person parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (Person) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//
//      private Object username_ = "";
//      /**
//       * <code>string username = 1;</code>
//       */
//      public String getUsername() {
//        Object ref = username_;
//        if (!(ref instanceof String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          String s = bs.toStringUtf8();
//          username_ = s;
//          return s;
//        } else {
//          return (String) ref;
//        }
//      }
//      /**
//       * <code>string username = 1;</code>
//       */
//      public com.google.protobuf.ByteString
//          getUsernameBytes() {
//        Object ref = username_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (String) ref);
//          username_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string username = 1;</code>
//       */
//      public Builder setUsername(
//          String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//
//        username_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string username = 1;</code>
//       */
//      public Builder clearUsername() {
//
//        username_ = getDefaultInstance().getUsername();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string username = 1;</code>
//       */
//      public Builder setUsernameBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  checkByteStringIsUtf8(value);
//
//        username_ = value;
//        onChanged();
//        return this;
//      }
//
//      private int age_ ;
//      /**
//       * <code>int32 age = 2;</code>
//       */
//      public int getAge() {
//        return age_;
//      }
//      /**
//       * <code>int32 age = 2;</code>
//       */
//      public Builder setAge(int value) {
//
//        age_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>int32 age = 2;</code>
//       */
//      public Builder clearAge() {
//
//        age_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private Object sex_ = "";
//      /**
//       * <code>string sex = 3;</code>
//       */
//      public String getSex() {
//        Object ref = sex_;
//        if (!(ref instanceof String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          String s = bs.toStringUtf8();
//          sex_ = s;
//          return s;
//        } else {
//          return (String) ref;
//        }
//      }
//      /**
//       * <code>string sex = 3;</code>
//       */
//      public com.google.protobuf.ByteString
//          getSexBytes() {
//        Object ref = sex_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (String) ref);
//          sex_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string sex = 3;</code>
//       */
//      public Builder setSex(
//          String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//
//        sex_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string sex = 3;</code>
//       */
//      public Builder clearSex() {
//
//        sex_ = getDefaultInstance().getSex();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string sex = 3;</code>
//       */
//      public Builder setSexBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  checkByteStringIsUtf8(value);
//
//        sex_ = value;
//        onChanged();
//        return this;
//      }
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.setUnknownFieldsProto3(unknownFields);
//      }
//
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.mergeUnknownFields(unknownFields);
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:Person)
//    }
//
//    // @@protoc_insertion_point(class_scope:Person)
//    private static final Person DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new Person();
//    }
//
//    public static Person getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static final com.google.protobuf.Parser<Person>
//        PARSER = new com.google.protobuf.AbstractParser<Person>() {
//      public Person parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//          return new Person(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<Person> parser() {
//      return PARSER;
//    }
//
//    @Override
//    public com.google.protobuf.Parser<Person> getParserForType() {
//      return PARSER;
//    }
//
//    public Person getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_Person_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_Person_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    String[] descriptorData = {
//      "\n\014person.proto\"4\n\006Person\022\020\n\010username\030\001 \001" +
//      "(\t\022\013\n\003age\030\002 \001(\005\022\013\n\003sex\030\003 \001(\tb\006proto3"
//    };
//    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
//        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
//          public com.google.protobuf.ExtensionRegistry assignDescriptors(
//              com.google.protobuf.Descriptors.FileDescriptor root) {
//            descriptor = root;
//            return null;
//          }
//        };
//    com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        }, assigner);
//    internal_static_Person_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_Person_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_Person_descriptor,
//        new String[] { "Username", "Age", "Sex", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
